export const MATH_FORMULAS = [
  "x = (-b ± √(b² - 4ac)) / 2a",
  "e^(iπ) + 1 = 0",
  "a² + b² = c²",
  "E = mc²",
  "∫ e^(-x²) dx = √π",
  "F = G (m₁m₂) / r²",
  "∇ · E = ρ / ε₀",
  "df/dt = lim(h→0) (f(t+h) - f(t))/h",
  "∑ (1/n²) = π²/6",
  "i² = -1",
  "cos²θ + sin²θ = 1",
  "lim(x→0) (sin x)/x = 1",
  "A = πr²",
  "P(A|B) = P(B|A)P(A) / P(B)",
  "S = k ln Ω",
  "Φ = ∮ E · dA = Q / ε₀",
  "sin(α ± β) = sin α cos β ± cos α sin β",
  "d/dx (x^n) = nx^(n-1)",
];
